# Generated by Django 5.0.6 on 2024-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('is_task_completed', models.BooleanField(default=False)),
                ('completed_task_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
