# Generated by Django 5.0.6 on 2024-05-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttodoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoapp',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6),
        ),
    ]
