# Generated by Django 5.0.6 on 2024-05-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirsttodoapp', '0002_todoapp_due_date_todoapp_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=6),
        ),
    ]
